<a href="https://colab.research.google.com/github/iduryodhanrao/ml-tests/blob/main/Loading_images_and_visualizing_their_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torchvision
import torchvision.transforms as transforms

In [ ]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

batch_size = 4

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,
                                          shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size,
                                         shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

100%|██████████| 170498071/170498071 [00:04<00:00, 40204735.24it/s]


Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# functions to show an image


def imshow(img):
    img = img / 2 + 0.5     # unnormalize
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))
    plt.show()

In [ ]:
# get some random training images
dataiter = iter(trainloader)
images, labels = next(dataiter)

In [ ]:
dataiter

In [ ]:
type(images)

torch.Tensor

In [ ]:
type(labels)

torch.Tensor

In [ ]:
images.shape

torch.Size([4, 3, 32, 32])

In [ ]:
labels.shape

torch.Size([4])

In [ ]:
images[3].shape

torch.Size([3, 32, 32])

In [ ]:
# Image Intencity of Various Channel: Iterate through Index
# 2=> Blue; 0=> Red ; 1 => Green
images[0][1]

tensor([[0.9059, 0.9059, 0.8588,  ..., 0.7098, 0.7020, 0.6784],
        [0.7961, 0.8353, 0.8588,  ..., 0.7020, 0.6941, 0.6627],
        [0.7725, 0.8039, 0.8353,  ..., 0.7647, 0.7490, 0.7020],
        ...,
        [0.0980, 0.1294, 0.1451,  ..., 0.0980, 0.0980, 0.0824],
        [0.0980, 0.1137, 0.0980,  ..., 0.0902, 0.0745, 0.0745],
        [0.0745, 0.0902, 0.0824,  ..., 0.0745, 0.0745, 0.0745]])

In [ ]:
images[0][2][7][6]

tensor(0.8745)

In [ ]:
images[0][0][7][6]

tensor(0.8275)

In [ ]:
# Find the blue color's intensity in pixel 7,6 in 1st image
images[0][2][7][6]

tensor(-0.1922)

In [ ]:
#Simplify the indexing
images[0,2,7,6]

tensor(-0.1922)

In [ ]:
# show images
imshow(torchvision.utils.make_grid(images))

In [ ]:
print(images[0])

tensor([[[ 0.8902,  0.4588, -0.2627,  ...,  0.9922,  0.9373,  1.0000],
         [ 0.7804,  0.4745, -0.2000,  ...,  0.7569,  0.7176,  0.9451],
         [ 0.7569,  0.5451, -0.1529,  ...,  0.1451,  0.6314,  0.6863],
         ...,
         [-0.2235, -0.1843, -0.0824,  ...,  0.3725,  0.7412,  0.6235],
         [-0.2863, -0.1765, -0.1529,  ...,  0.3176,  0.7098,  0.6549],
         [-0.2627, -0.2392, -0.1765,  ...,  0.2549,  0.5294,  0.6392]],

        [[ 0.9059,  0.4588, -0.2941,  ...,  0.9922,  0.9373,  1.0000],
         [ 0.7804,  0.4510, -0.2392,  ...,  0.7569,  0.7176,  0.9529],
         [ 0.7490,  0.5059, -0.2078,  ...,  0.1451,  0.6235,  0.6784],
         ...,
         [-0.1059, -0.0745,  0.0196,  ...,  0.3804,  0.7255,  0.6157],
         [-0.1451, -0.0510, -0.0431,  ...,  0.3490,  0.6706,  0.6627],
         [-0.1059, -0.0980, -0.0510,  ...,  0.2314,  0.4980,  0.6392]],

        [[ 0.9059,  0.1608, -0.6627,  ...,  0.9843,  0.9373,  1.0000],
         [ 0.7569,  0.1686, -0.6471,  ...,  0

In [ ]:
print(labels)

tensor([8, 6, 4, 3])
